add healthcheck + smart deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -44,9 +44,49 @@ jobs:
     needs: build
 
     steps:
-      - name: Pull and run container
+      - name: Deploy with smart rollback
         run: |
-          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mini-devops-app:${{ needs.build.outputs.tag }}
+          TAG=${{ needs.build.outputs.tag }}
+          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/mini-devops-app
+
+          echo "Deployando versión $TAG"
+
+          # 1. Guardar versión actual
+          CURRENT=$(docker ps --format "{{.Image}}" | grep mini-devops-app || true}
+          echo "Versión actual: $CURRENT"
+
+          # 2. Traer nueva imagen
+          docker pull $IMAGE:$TAG
+
+          # 3. Levantar nueva versión
           docker stop app || true
           docker rm app || true
-          docker run -d -p 5000:5000 --name app ${{ secrets.DOCKERHUB_USERNAME }}/mini-devops-app:${{ needs.build.outputs.tag }}
+          docker run -d -p 5000:5000 --name app $IMAGE:$TAG
+
+          # 4. Esperar a que arranque
+          echo "Esperando 10 segundos..."
+          sleep 10
+
+          # 5. Verificar health
+          STATUS=$(docker inspect --format='{{.State.Health.Status}}' app 2>/dev/null || echo "fail")
+
+          echo "Estado del container: $STATUS"
+
+          # 6. Si falla → rollback
+          if [ "$STATUS" != "healthy" ]; then
+            echo "❌ Falló el deploy, haciendo rollback..."
+
+            docker stop app || true
+            docker rm app || true
+
+            if [ -n "$CURRENT" ]; then
+              docker run -d -p 5000:5000 --name app $CURRENT
+              echo "✅ Volvió a $CURRENT"
+            else
+              echo "⚠️ No había versión previa"
+            fi
+
+            exit 1
+          fi
+
+          echo "✅ Deploy OK"
